In [1]:
import numpy as np

In [6]:
D = np.fromfile("./saved_npy_data/result_distance_float32_10000_100_raw", dtype=np.float32)
I = np.fromfile("./saved_npy_data/result_index_int32_10000_100_raw", dtype=np.int32)
xq = np.fromfile("./saved_npy_data/query_vectors_float32_10000_128_raw", dtype=np.float32)
D = D.reshape(10000,100)
I = I.reshape(10000,100)
xq = xq.reshape(10000,128)

In [7]:
print("==== Distance ====\n\n{}\nshape: {}\n".format(D, D.shape))
print("==== Index ====\n\n{}\nshape: {}\n".format(I, I.shape))

==== Distance ====

[[50993.203 54336.414 56335.76  ... 65039.16  65092.453 65136.562]
 [28778.004 29403.02  29605.914 ... 38942.62  38943.63  38955.61 ]
 [35337.684 35693.312 35995.484 ... 43081.79  43117.96  43128.875]
 ...
 [47332.293 48143.83  49028.484 ... 58328.45  58379.38  58422.836]
 [38902.82  39315.617 41596.766 ... 53518.285 53519.25  53557.53 ]
 [37481.633 39034.703 39707.74  ... 52359.676 52385.773 52396.105]]
shape: (10000, 100)

==== Index ====

[[672303424 615142912 204071728 ... 905142912 277061600 603696064]
 [328569856 455604832 337592352 ... 356877120  25276548 721982912]
 [397763200 207300896 924963264 ... 447729952 522492192 827586304]
 ...
 [261386448 423027872 456076416 ... 134056272  68733064 505049952]
 [443633952 433375200 935973632 ... 112122144 847878848 241995424]
 [193715216 266287264 883319936 ... 493088000 625182016 918522752]]
shape: (10000, 100)



In [8]:
print("Xq\ttype: {}\tshape: {}\n".format(type(xq), xq.shape))
print(xq[0], xq[0].shape) 
# Why like integers? -> The sift1b dataset actually stores vector in uint8 format, to save space
#   size = 132000000000 bytes = (128 bytes vector + 4 bytes index) * 1B
print(xq[0][0])

Xq	type: <class 'numpy.ndarray'>	shape: (10000, 128)

[  3.   9.  17.  78.  83.  15.  10.   8. 101. 109.  21.   8.   3.   2.
   9.  64.  39.  31.  18.  80.  55.  10.   2.  12.   7.   7.  26.  58.
  32.   6.   4.   3.  14.   2.  13.  28.  37.  19.  47.  59. 109.  22.
   2.   6.  18.  15.  20. 109.  30.   8.  11.  44. 109.  54.  19.  32.
  17.  21.  15.  22.  12.  28. 101.  35.  66.  11.   9.  30.  68.  35.
  30.  75. 106. 103.  26.  50.  76.  20.   8.  13.  51.  41.  63. 109.
  40.   2.   3.  15.  36.  49.  21.  13.  12.   9.  36.  37.  52.  37.
  24.  34.  19.   3.  13.  23.  21.   8.   3.  20.  68.  56.  79.  60.
  99.  36.   7.  28.  78.  41.   7.  21.  74.  26.   3.  15.  34.  15.
  12.  27.] (128,)
3.0


In [11]:
PQ_quantizer = np.fromfile("./saved_npy_data/PQ_quantizer_float32_16_256_8_raw", dtype=np.float32)
coarse_cen = np.fromfile("./saved_npy_data/coarse_centers_float32_8192_128_raw", dtype=np.float32)
PQ_quantizer = PQ_quantizer.reshape(16,256,8)
coarse_cen = coarse_cen.reshape(8192,128)

In [12]:
print("==== Sub-quantizer ====\n{}\n\nshape:{}\n".format(PQ_quantizer, PQ_quantizer.shape))
print("==== Coarse-quantizer ====\n{}\n\nshape:{}\n".format(coarse_cen, coarse_cen.shape))

==== Sub-quantizer ====
[[[-1.39830580e+01 -9.50784492e+00 -3.96348667e+00 ...  5.86917877e+00
    1.04514023e+02  1.04102793e+01]
  [-6.90511627e+01 -2.03367958e+01  2.62607670e+00 ...  2.83390975e+00
    1.95819175e+00 -8.36786938e+00]
  [-4.25987320e+01 -9.93877316e+00  1.04937162e+01 ... -1.98086727e+00
   -6.30460835e+00 -2.12152977e+01]
  ...
  [ 1.92724438e+01  2.98870945e+00 -6.91194391e+00 ...  1.94331989e+01
   -9.75370109e-01 -8.94906640e-01]
  [ 2.05092468e+01 -1.09992886e+00 -9.42241001e+00 ...  9.38970661e+00
   -7.21518993e+00 -4.89512920e+00]
  [ 1.51460276e+01  1.51528549e+00 -1.98966455e+00 ... -1.96080756e+00
   -1.24802208e+00  4.54244643e-01]]

 [[-1.38893576e+01 -1.30567741e+01  1.27895641e+01 ... -1.25062037e+00
    4.34972916e+01  7.75580406e+00]
  [ 1.04570885e+01  3.74349747e+01  1.84257901e+00 ... -4.78825521e+00
    1.15119820e+01  5.44087677e+01]
  [-1.12493572e+01 -3.95343399e+00  1.05285339e+01 ... -1.15094595e+01
   -1.70058894e+00 -4.81053877e+00]
  ...

In [16]:
#########    Cell Contents   #########
list_id = 124
code_num = 81713
list_ids = np.fromfile("./saved_npy_data/cells/list_{}_IDs_int32_{}_raw".format(list_id, code_num), dtype=np.int32)
list_codes = np.fromfile("./saved_npy_data/cells/list_{}_codes_uint8_{}_16_raw".format(list_id, code_num), dtype=np.uint8)
list_codes = list_codes.reshape(code_num, 16)

In [17]:
print("==== Vector IDs ====\n{}\n\nshape: {}\n".format(list_ids, list_ids.shape))
print("==== PQ codes ====\n{}\n\nshape: {}\n".format(list_codes, list_codes.shape))

==== Vector IDs ====
[     7330     15876     19023 ... 999967925 999970701 999994567]

shape: (81713,)

==== PQ codes ====
[[232 237  49 ...  65 119  71]
 [ 49   0 156 ... 169  13  25]
 [169 193 103 ...  53 252 104]
 ...
 [234 237 225 ... 142 209 251]
 [234 157 140 ...  85  57 218]
 [147   2 146 ...  37  71 118]]

shape: (81713, 16)



In [18]:
######### Debug INFO    ######

debug_searched_cell_ids = np.fromfile(
    "./saved_npy_data/debug_searched_cell_ids_int32_batch_size_64_nprobe_32_raw", dtype=np.int32)
debug_searched_cell_dist = np.fromfile(
    "./saved_npy_data/debug_searched_cell_dist_float32_batch_size_64_nprobe_32_raw", dtype=np.float32)
debug_dist_table = np.fromfile(
    "./saved_npy_data/debug_dist_table_float32_batch_size_64_nprobe_32_K_256_M_16_raw", dtype=np.float32)

In [19]:
debug_searched_cell_ids = debug_searched_cell_ids.reshape(64, 32)
debug_searched_cell_dist = debug_searched_cell_dist.reshape(64, 32)
debug_dist_table = debug_dist_table.reshape(64, 32, 256, 16)

In [20]:
print("\n\n========= debug_searched_cell_ids ==========\n\n {}".format(debug_searched_cell_ids))
print("\n\n========= debug_searched_cell_dist ==========\n\n {}".format(debug_searched_cell_dist))
print("\n\n========= debug_dist_table ==========\n\n {}".format(debug_dist_table))



========= debug_searched_cell_ids ==========

 [[4121 3860 4300 ... 2742 2458 5387]
 [6881 3260 2789 ... 5687 2610 7870]
 [4829  812 1804 ... 1021 6681 3395]
 ...
 [6205 2292  576 ... 6537 2087 1881]
 [ 967 4399 6224 ... 2752 4737   20]
 [1897 6211  308 ... 6099 6731 4720]]


========= debug_searched_cell_dist ==========

 [[ 71414.47   71604.61   72159.05  ...  89657.016  89919.484  90270.76 ]
 [ 52572.49   55069.695  69131.484 ...  96507.64   96834.66   97047.64 ]
 [ 46726.44   46823.887  52429.11  ...  74583.     74809.03   75589.445]
 ...
 [ 74964.53   79775.97   80021.87  ...  99823.805 100500.58  100640.36 ]
 [ 23077.234  38605.473  41923.83  ...  61805.812  62166.65   64026.254]
 [ 34439.617  34704.875  43361.86  ...  74679.61   74836.13   74932.945]]


========= debug_dist_table ==========

 [[[[19250.639   14268.577    3969.4128  ...  6585.9224   6474.6904
     1073.1978 ]
   [ 6771.1074   2025.872    3256.8865  ...  6152.3477   4997.516
     2141.3613 ]
   [ 2142.566    758